import { useEffect, useState } from 'react';
import { Activity, CheckCircle2, ClipboardList, Globe2, HeartPulse, History, Network, RefreshCw, Server, ShieldCheck, Users } from 'lucide-react';
import { centralApiUrl, tokenHeaders } from './config';

type View = 'dashboard' | 'hospitals' | 'federated-rounds' | 'models' | 'performance' | 'audit-logs';
type Dashboard = { totalHospitals: number; activeHospitals: number; currentRound: number; globalVersion: number; updatesReceived: number; systemHealth: string; activeRound?: Round };
type Hospital = { _id?: string; hospitalName?: string; email: string; createdAt?: string };
type Round = { id?: string; _id?: string; round: number; status: string; baseGlobalModelVersion: number; resultingGlobalModelVersion?: number; expectedParticipantCount: number; submittedParticipantCount: number; remainingParticipantCount: number; totalSamples: number; participantHospitalIds: string[]; submittedHospitalIds: string[]; createdAt?: string; completedAt?: string; version?: number; hospitals?: number; samples?: number; aggregationTimestamp?: string };
type Model = { _id?: string; version: number; round: number; samples: number; hospitals: number; status: string; createdAt?: string };
type Update = { _id?: string; hospitalId: string; round: number; samples: number; payloadBytes?: number; receivedAt?: string; metrics?: { loss?: number; accuracy?: number } };
type Audit = { _id?: string; actorId: string; actorRole: string; action: string; target?: string; createdAt?: string };
const nav: Array<[View, string, typeof Activity]> = [['dashboard', 'Overview', Activity], ['hospitals', 'Connected Hospitals', Users], ['federated-rounds', 'Federated Rounds', Network], ['models', 'Global Model', Globe2], ['performance', 'Performance', ClipboardList], ['audit-logs', 'Audit Logs', History]];
const api = async <T,>(path: string, options: RequestInit = {}) => { const response = await fetch(centralApiUrl + path, { ...options, headers: { ...options.headers, ...tokenHeaders() } }); const data = response.status === 204 ? undefined : await response.json(); if (!response.ok) { if (response.status === 401) window.dispatchEvent(new Event('arogyavaani:session-expired')); throw new Error(data?.message ?? 'Request failed.'); } return data as T; };
const date = (value?: string) => value ? new Date(value).toLocaleString() : 'Not available';
function Metric({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="metric"><div className="metric-label">{label}<span className="metric-dot" /></div><strong>{value}</strong><small>{detail}</small></div>; }
function Empty({ children }: { children: string }) { return <section className="panel empty-state">{children}</section>; }

export function Admin({ onExit, path, onNavigate }: { onExit: () => void; path: string; onNavigate: (path: string) => void }) {
  const requested = path.replace('/admin/', '') as View; const view: View = nav.some(([id]) => id === requested) ? requested : 'dashboard';
  const [dashboard, setDashboard] = useState<Dashboard | null>(null); const [hospitals, setHospitals] = useState<Hospital[]>([]); const [rounds, setRounds] = useState<Round[]>([]); const [models, setModels] = useState<Model[]>([]); const [updates, setUpdates] = useState<Update[]>([]); const [audits, setAudits] = useState<Audit[]>([]); const [selected, setSelected] = useState<string[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const refresh = async () => { setLoading(true); setError(''); try { if (view === 'dashboard') { const [nextDashboard, nextHospitals, nextRounds] = await Promise.all([api<Dashboard>('/api/admin/dashboard'), api<Hospital[]>('/api/admin/hospitals'), api<Round[]>('/api/admin/federated-rounds')]); setDashboard(nextDashboard); setHospitals(nextHospitals); setRounds(nextRounds); } else if (view === 'hospitals') setHospitals(await api('/api/admin/hospitals')); else if (view === 'federated-rounds') setRounds(await api('/api/admin/federated-rounds')); else if (view === 'models') setModels(await api('/api/admin/models')); else if (view === 'performance') setUpdates(await api('/api/admin/model-updates')); else if (view === 'audit-logs') setAudits(await api('/api/admin/audit-logs')); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to load administrator data.'); } finally { setLoading(false); } };
  useEffect(() => { void refresh(); const poll = view === 'dashboard' || view === 'federated-rounds' ? window.setInterval(() => void refresh(), 5000) : undefined; return () => { if (poll) window.clearInterval(poll); }; }, [view]);
  const createRound = async () => { setBusy(true); setError(''); try { await api('/api/federated/rounds', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ participantHospitalIds: selected }) }); setSelected([]); await refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to create federated round.'); } finally { setBusy(false); } };
  const cancelRound = async (round: number) => { setBusy(true); setError(''); try { await api(`/api/federated/rounds/${round}/cancel`, { method: 'POST' }); await refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to cancel federated round.'); } finally { setBusy(false); } };
  const aggregate = createRound;
  const current = rounds.find(item => !['COMPLETED', 'CANCELLED', 'CLOSED'].includes(item.status)) ?? dashboard?.activeRound; const participation = current?.expectedParticipantCount ? Math.round(current.submittedParticipantCount / current.expectedParticipantCount * 100) : 0;
  const heading: Record<View, [string, string]> = { dashboard: ['Network overview', 'Monitor federated activity without accessing hospital datasets.'], hospitals: ['Connected hospitals', 'Registered hospital metadata and access to the federated network.'], 'federated-rounds': ['Federated rounds', 'Completed rounds and aggregation metadata.'], models: ['Global model', 'Aggregated global-model metadata only.'], performance: ['Performance', 'Metrics submitted with model updates, when available.'], 'audit-logs': ['Audit logs', 'Privacy-safe administrative activity.'] };
  const content = () => {
    if (loading) return <Empty>Loading administrator data…</Empty>;
    if (view === 'dashboard' && dashboard) return <><section className="metrics-grid"><Metric label="REGISTERED HOSPITALS" value={String(dashboard.totalHospitals)} detail="Accounts in the network" /><Metric label="ACTIVE ROUND" value={current ? String(current.round) : 'None'} detail={current?.status ?? 'Create a participant round'} /><Metric label="GLOBAL MODEL" value={dashboard.globalVersion ? `v${dashboard.globalVersion}` : 'v0'} detail={current ? `Round base: v${current.baseGlobalModelVersion}` : 'No model aggregated'} /><Metric label="ROUND PROGRESS" value={current ? `${current.submittedParticipantCount}/${current.expectedParticipantCount}` : '—'} detail={current ? `${current.remainingParticipantCount} hospitals pending` : 'No active round'} /></section><section className="panel"><div className="panel-title"><div><h2>Federated round management</h2><p>Select the hospitals required for the next asynchronous round. Aggregation begins only after every selected hospital submits.</p></div><button className="button primary" disabled={busy || !selected.length || Boolean(current)} onClick={() => void createRound()}>{busy ? 'Creating…' : `Start round (${selected.length})`}</button></div>{current ? <><div className="round-stats"><div><b>v{current.baseGlobalModelVersion}</b><span>Base model</span></div><div><b>{current.submittedParticipantCount}<small> / {current.expectedParticipantCount}</small></b><span>{current.status}</span></div><div><b>{current.remainingParticipantCount}</b><span>Hospitals pending</span></div></div><div className="progress"><span style={{ width: `${participation}%` }} /></div><p>{current.participantHospitalIds.map(email => `${current.submittedHospitalIds.includes(email) ? '✓' : '⌛'} ${email}`).join(' · ')}</p>{['ACTIVE', 'WAITING_FOR_UPDATES', 'READY_FOR_AGGREGATION'].includes(current.status) && <button className="button secondary" disabled={busy} onClick={() => void cancelRound(current.round)}>Cancel incomplete round</button>}</> : <div className="hospital-table"><table><thead><tr><th>SELECT</th><th>HOSPITAL</th><th>EMAIL</th></tr></thead><tbody>{hospitals.map(item => <tr key={item.email}><td><input type="checkbox" checked={selected.includes(item.email)} onChange={() => setSelected(value => value.includes(item.email) ? value.filter(email => email !== item.email) : [...value, item.email])} /></td><td>{item.hospitalName ?? 'Not provided'}</td><td>{item.email}</td></tr>)}</tbody></table></div>}</section></>;
    if (view === 'dashboard' && dashboard) return <><section className="metrics-grid"><Metric label="REGISTERED HOSPITALS" value={String(dashboard.totalHospitals)} detail={`${dashboard.activeHospitals} submitted in current round`} /><Metric label="CURRENT ROUND" value={String(dashboard.currentRound)} detail={dashboard.updatesReceived ? 'Updates available' : 'Waiting for updates'} /><Metric label="GLOBAL MODEL" value={dashboard.globalVersion ? `v${dashboard.globalVersion}` : 'Not available'} detail={current?.status ?? 'No model yet'} /><Metric label="UPDATES RECEIVED" value={String(dashboard.updatesReceived)} detail={`${participation}% of registered hospitals`} /></section><div className="admin-grid"><section className="panel"><div className="panel-title"><div><h2>Aggregation control</h2><p>Runs protected weighted FedAvg on available binary model updates.</p></div><button className="button primary" disabled={busy || !dashboard.updatesReceived} onClick={() => void aggregate()}><Network size={16} /> {busy ? 'Aggregating…' : 'Aggregate updates'}</button></div><div className="admin-progress"><div><strong>{participation}%</strong><span>participation</span></div><div className="progress"><span style={{ width: `${participation}%` }} /></div><div><strong>{dashboard.updatesReceived}</strong><span>updates</span></div></div><div className="admin-status"><CheckCircle2 size={17} /><span><b>Privacy boundary enforced.</b> The central service stores model updates and operational metadata, not patient images.</span></div></section><section className="panel"><h2>System health</h2><div className="health-row"><Server size={17} /><span>Coordination API</span><b>{dashboard.systemHealth}</b></div><div className="health-row"><Globe2 size={17} /><span>Global model store</span><b>{dashboard.globalVersion ? 'Available' : 'No model yet'}</b></div><div className="health-row"><Activity size={17} /><span>Active round</span><b>{dashboard.updatesReceived ? 'Updates received' : 'Waiting'}</b></div></section></div></>;
    if (view === 'hospitals') return hospitals.length ? <Table headings={['Hospital', 'Email', 'Registered']} rows={hospitals.map(item => [item.hospitalName ?? 'Not provided', item.email, date(item.createdAt)])} /> : <Empty>No hospitals connected yet.</Empty>;
    if (view === 'federated-rounds') return rounds.length ? <Table headings={['Round', 'Base model', 'Progress', 'Participants', 'Status', 'Result']} rows={rounds.map(item => [String(item.round), `v${item.baseGlobalModelVersion}`, `${item.submittedParticipantCount}/${item.expectedParticipantCount}`, item.participantHospitalIds.map(email => item.submittedHospitalIds.includes(email) ? `✓ ${email}` : `⌛ ${email}`).join(', '), item.status, item.resultingGlobalModelVersion ? `v${item.resultingGlobalModelVersion}` : date(item.completedAt)])} /> : <Empty>No federated rounds yet.</Empty>;
    if (view === 'models') return models.length ? <Table headings={['Version', 'Round', 'Hospitals', 'Samples', 'Status', 'Created']} rows={models.map(item => [`v${item.version}`, String(item.round), String(item.hospitals), String(item.samples), item.status, date(item.createdAt)])} /> : <Empty>No global model available.</Empty>;
    if (view === 'performance') return updates.length ? <Table headings={['Hospital', 'Round', 'Samples', 'Loss', 'Accuracy']} rows={updates.map(item => [item.hospitalId, String(item.round), String(item.samples), item.metrics?.loss === undefined ? 'Not reported' : item.metrics.loss.toFixed(4), item.metrics?.accuracy === undefined ? 'Not reported' : `${(item.metrics.accuracy * 100).toFixed(1)}%`])} /> : <Empty>No performance metadata has been submitted.</Empty>;
    if (view === 'audit-logs') return audits.length ? <Table headings={['Time', 'Actor', 'Role', 'Action', 'Target']} rows={audits.map(item => [date(item.createdAt), item.actorId, item.actorRole, item.action, item.target ?? '—'])} /> : <Empty>No audit events available.</Empty>;
    return null;
  };
  return <div className="admin-shell"><header className="admin-top"><div className="brand"><div className="brand-mark"><HeartPulse size={21} /></div><div><b>Arogya<span>Vaani</span></b><small>Network operations</small></div></div><div className="admin-user"><div className="avatar">AD</div><div><b>Administrator session</b><span>Role-restricted access</span></div><button onClick={onExit}>Sign out</button></div></header><div className="admin-tabs" aria-label="Administrator navigation">{nav.map(([id, label, Icon]) => <button className={view === id ? 'active' : ''} key={id} onClick={() => onNavigate(`/admin/${id}`)}><Icon size={15} />{label}</button>)}</div><main className="admin-main"><section className="page-heading"><div><div className="eyebrow">ADMINISTRATION</div><h1>{heading[view][0]}</h1><p>{heading[view][1]}</p></div><button className="button secondary" onClick={() => void refresh()} disabled={loading}><RefreshCw size={15} /> {loading ? 'Refreshing…' : 'Refresh'}</button></section>{error && <div className="form-error" role="alert">{error}</div>}{content()}<div className="admin-privacy"><ShieldCheck size={19} /><span><b>Privacy-preserved monitoring</b> Administrators see model and participation metadata, never hospital image collections.</span></div></main></div>;
}
function Table({ headings, rows }: { headings: string[]; rows: string[][] }) { return <section className="panel hospital-table"><table><thead><tr>{headings.map(heading => <th key={heading}>{heading}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index}>{row.map((cell, cellIndex) => <td key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table></section>; }
