import { useEffect, useRef, useState } from 'react';
import { Activity, ArrowRight, BrainCircuit, FolderUp, History, LayoutDashboard, LogOut, ScanSearch, Server, ShieldCheck } from 'lucide-react';
import { centralApiUrl, localMlUrl, tokenHeaders } from './config';
import { LiveFederated } from './LiveFederated';
import { Prediction } from './Prediction';
import './dashboard.css';

type View = 'overview' | 'train' | 'global-model' | 'prediction' | 'history';
type Validation = { classes: string[]; class_distribution: Record<string, number>; file_count: number; size_bytes: number };
type SelectedDataset = { folderName: string; files: File[]; classes: string[]; classDistribution: Record<string, number>; fileCount: number; sizeBytes: number };
type Training = { status: string; epoch?: number; total_epochs?: number; loss?: number; accuracy?: number; checkpoint?: string; message?: string; samples?: number };
type NetworkStatus = { version: number; round: number; updatesReceived: number; hospitals: number; aggregationStatus: string; baseGlobalModelVersion?: number; isParticipant?: boolean };
type OverviewData = { hospitalName: string; connectionStatus: string; globalModel: { version: number; round: number; status: string; updatedAt?: string } | null; currentRound: number; round?: { status: string; baseGlobalModelVersion: number; submittedParticipantCount: number; expectedParticipantCount: number; resultingGlobalModelVersion?: number; isParticipant: boolean; hasSubmitted: boolean; completedAt?: string }; training: Training & { updatedAt?: string }; participationStatus: string; lastContribution: { round: number; samples: number; receivedAt: string } | null };

const nav: Array<[View, string, typeof LayoutDashboard]> = [['overview', 'Overview', LayoutDashboard], ['train', 'Local Training', BrainCircuit], ['global-model', 'Global Model', Server], ['prediction', 'Clinical Prediction', ScanSearch], ['history', 'Training History', History]];
const date = (value?: string) => value ? new Date(value).toLocaleString() : 'Not available';
const Metric = ({ label, value, detail }: { label: string; value: string; detail: string }) => <div className="metric"><div className="metric-label">{label}<span className="metric-dot green" /></div><strong>{value}</strong><small>{detail}</small></div>;

function Overview({ setView }: { setView: (view: View) => void }) {
  const [data, setData] = useState<OverviewData | null>(null);
  const [error, setError] = useState('');
  useEffect(() => { fetch(centralApiUrl + '/api/hospital/overview', { headers: tokenHeaders() }).then(async response => { const body = await response.json(); if (!response.ok) throw new Error(body.message); setData(body); }).catch(cause => setError(cause instanceof Error ? cause.message : 'Unable to load hospital overview.')); }, []);
  return <><section className="page-heading"><div><div className="eyebrow">HOSPITAL WORKSPACE</div><h1>{data?.hospitalName ?? 'Hospital overview'}</h1><p>Current federated-network information for this hospital.</p></div><button className="button primary" onClick={() => setView('train')}><BrainCircuit size={17} /> Start Local Training</button></section>{error && <div className="form-error">{error}</div>}{data && <><section className="metrics-grid"><Metric label="CONNECTION" value={data.connectionStatus} detail="Central coordination API" /><Metric label="GLOBAL MODEL" value={data.globalModel ? `v${data.globalModel.version}` : 'Not available'} detail={data.globalModel?.status ?? 'No model aggregated'} /><Metric label="CURRENT ROUND" value={data.currentRound ? String(data.currentRound) : 'None'} detail={data.participationStatus} /><Metric label="LOCAL TRAINING" value={data.training.status} detail={date(data.training.updatedAt)} /></section><section className="panel contribution-summary"><h2>Federated learning / current round</h2>{data.round ? <p>Round {data.currentRound} · {data.round.isParticipant ? 'Participating' : 'Not selected'} · Base model v{data.round.baseGlobalModelVersion} · {data.round.hasSubmitted ? 'Update submitted' : 'Update pending'} · {data.round.submittedParticipantCount}/{data.round.expectedParticipantCount} complete · {data.round.status}{data.round.resultingGlobalModelVersion ? ` · Global model v${data.round.resultingGlobalModelVersion}` : ''}</p> : <p>No active federated round has selected this hospital.</p>}</section><section className="panel contribution-summary"><h2>Last contribution</h2>{data.lastContribution ? <p>Round {data.lastContribution.round} · {data.lastContribution.samples.toLocaleString()} local samples · submitted {date(data.lastContribution.receivedAt)}</p> : <p>No model update has been submitted by this hospital yet.</p>}</section></>}<section className="principle"><ShieldCheck size={20} /><div><b>Privacy boundary</b><p>Patient images remain inside your hospital environment. Only model updates and limited training metadata are shared with the central server.</p></div></section></>;
}

function LocalTrain() {
  const [datasetDir, setDatasetDir] = useState(''); const [epochs, setEpochs] = useState(1); const [classes, setClasses] = useState(2);
  const [validation, setValidation] = useState<Validation | null>(null); const [training, setTraining] = useState<Training>({ status: 'idle' }); const [network, setNetwork] = useState<NetworkStatus | null>(null);
  const [selectedDataset, setSelectedDataset] = useState<SelectedDataset | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [submitted, setSubmitted] = useState(''); const [uploadNotice, setUploadNotice] = useState('');
  const datasetInput = useRef<HTMLInputElement | null>(null);
  const record = async (status: Training) => { if (!['queued', 'validating', 'training', 'completed', 'failed'].includes(status.status)) return; await fetch(centralApiUrl + '/api/training/runs', { method: 'POST', headers: { 'Content-Type': 'application/json', ...tokenHeaders() }, body: JSON.stringify({ status: status.status, samples: status.samples, loss: status.loss, accuracy: status.accuracy, checkpoint: status.checkpoint, message: status.message, epochs, completedAt: ['completed', 'failed'].includes(status.status) ? new Date().toISOString() : undefined }) }); };
  const refreshNetwork = async () => { try { const response = await fetch(centralApiUrl + '/api/federated/status', { headers: tokenHeaders() }); const body = await response.json(); if (!response.ok) throw new Error(body.message); setNetwork(body); } catch { /* Local training remains available when the coordination API is offline. */ } };
  useEffect(() => { void refreshNetwork(); }, []);
  useEffect(() => { if (!['queued', 'validating', 'training'].includes(training.status)) return; const poll = window.setInterval(() => { fetch(localMlUrl + '/training/status').then(response => response.json()).then(async next => { setTraining(next); if (['completed', 'failed'].includes(next.status)) await record(next); }).catch(() => setError('Unable to read local training progress.')); }, 1500); return () => window.clearInterval(poll); }, [training.status]);
  const selectDataset = (nextFiles: File[]) => {
    setError(''); setUploadNotice(''); setSubmitted(''); setDatasetDir(''); setValidation(null);
    if (!nextFiles.length) return;
    if (nextFiles.length > 20_000) { setError('Dataset contains too many files. The maximum is 20,000 files.'); return; }
    const sizeBytes = nextFiles.reduce((total, file) => total + file.size, 0);
    if (sizeBytes > 1_000_000_000) { setError('Dataset exceeds the 1 GB local upload limit.'); return; }
    const supported = /\.(jpe?g|png|bmp|tiff?|webp)$/i;
    const unsupported = nextFiles.find(file => !supported.test(file.name));
    if (unsupported) { setError(`Unsupported file "${unsupported.name}". Only JPG, JPEG, PNG, BMP, TIFF, and WEBP images are allowed.`); return; }
    const paths = nextFiles.map(file => (file.webkitRelativePath || '').replace(/\\/g, '/').split('/').filter(Boolean));
    if (paths.some(parts => parts.length < 3)) { setError('Select the parent dataset folder (for example chest_xray), not individual files or a class folder.'); return; }
    const folderName = paths[0][0];
    if (paths.some(parts => parts[0] !== folderName)) { setError('Select one complete dataset folder at a time.'); return; }
    const classDistribution = paths.reduce<Record<string, number>>((result, parts) => { result[parts[1]] = (result[parts[1]] ?? 0) + 1; return result; }, {});
    const detectedClasses = Object.keys(classDistribution).sort();
    if (detectedClasses.length < 2) { setError('Dataset must contain at least two class folders, such as NORMAL and PNEUMONIA.'); return; }
    setSelectedDataset({ folderName, files: nextFiles, classes: detectedClasses, classDistribution, fileCount: nextFiles.length, sizeBytes });
  };
  const clearDataset = () => { setSelectedDataset(null); setDatasetDir(''); setValidation(null); setClasses(2); setUploadNotice(''); setError(''); setSubmitted(''); if (datasetInput.current) datasetInput.current.value = ''; };
  const uploadDataset = async () => { if (!selectedDataset) return; setBusy(true); setError(''); setUploadNotice(''); setSubmitted(''); try { const body = new FormData(); selectedDataset.files.forEach(file => body.append('files', file, file.webkitRelativePath)); const response = await fetch(localMlUrl + '/dataset/upload', { method: 'POST', body }); const data = await response.json(); if (!response.ok) throw new Error(data.detail ?? 'Dataset preparation failed.'); const nextValidation = data.validation as Validation; setDatasetDir(data.dataset_dir); setValidation(nextValidation); setClasses(nextValidation.classes.length); setUploadNotice(`${data.dataset_name ?? selectedDataset.folderName} is validated and ready in hospital-local storage. ${nextValidation.file_count.toLocaleString()} images were sent only to ${localMlUrl}.`); } catch (cause) { setError(cause instanceof TypeError ? 'Local ML service is not running. Start the FastAPI service on 127.0.0.1:8000.' : cause instanceof Error ? cause.message : 'Dataset preparation failed.'); } finally { setBusy(false); } };
  const train = async () => { if (!datasetDir || !validation) return; if (!network?.round || !network.isParticipant) { setError('No active round selects this hospital. Local training can continue when an administrator starts a round.'); return; } setBusy(true); setError(''); setSubmitted(''); try { if ((network.baseGlobalModelVersion ?? 0) > 0) { const sync = await fetch(localMlUrl + '/federated/download-global', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ api_url: centralApiUrl, token: sessionStorage.getItem('arogyavaani_token'), expected_version: network.baseGlobalModelVersion }) }); const synced = await sync.json(); if (!sync.ok) throw new Error(synced.detail ?? `Unable to synchronize required global model v${network.baseGlobalModelVersion}.`); } const response = await fetch(localMlUrl + '/train', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ dataset_dir: datasetDir, num_classes: classes, epochs }) }); const data = await response.json(); if (!response.ok) throw new Error(data.detail ?? 'Local training failed.'); setTraining(data); await record(data); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Local training failed.'); } finally { setBusy(false); } };
  const submit = async () => { setBusy(true); setError(''); try { const statusResponse = await fetch(centralApiUrl + '/api/federated/status', { headers: tokenHeaders() }); const status = await statusResponse.json() as NetworkStatus; if (!statusResponse.ok || !status.round || !status.isParticipant) throw new Error('This hospital is not selected for an active federated round.'); const response = await fetch(localMlUrl + '/federated/submit', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ api_url: centralApiUrl, token: sessionStorage.getItem('arogyavaani_token'), round: status.round, checkpoint_path: training.checkpoint }) }); const data = await response.json(); if (!response.ok) throw new Error(data.detail ?? 'Model update submission failed.'); setSubmitted(`Update submitted for round ${status.round}. ${Number(data.bytes).toLocaleString()} model bytes were shared; no images were sent. ${data.remainingParticipantCount ? `${data.remainingParticipantCount} selected hospitals are still pending.` : 'Aggregation is starting.'}`); await refreshNetwork(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Model update submission failed.'); } finally { setBusy(false); } };
  return <>
    <section className="page-heading">
      <div><div className="eyebrow">LOCAL TRAINING</div><h1>Train a hospital-local model</h1><p>Select the parent dataset folder. X-ray images are prepared only by the local Python service and never sent to the central API.</p></div>
    </section>
    {network && <section className="training-context"><div><span>Required base model</span><b>v{network.baseGlobalModelVersion ?? 0}</b></div><div><span>Federated round</span><b>{network.round || 'No active round'}</b></div><div><span>Participation</span><b>{network.isParticipant ? `${network.updatesReceived}/${network.hospitals} submitted` : network.round ? 'Not selected' : 'Awaiting admin'}</b></div><div><span>Round status</span><b>{network.aggregationStatus}</b></div></section>}
    <section className="panel upload-panel">
      <div className="dataset-upload-field" role="button" tabIndex={0} onClick={() => datasetInput.current?.click()} onKeyDown={event => { if (event.key === 'Enter' || event.key === ' ') datasetInput.current?.click(); }}>
        <input ref={node => { datasetInput.current = node; node?.setAttribute('webkitdirectory', ''); }} type="file" multiple accept=".jpg,.jpeg,.png,.bmp,.tif,.tiff,.webp" hidden onChange={event => selectDataset(Array.from(event.target.files ?? []))} />
        <FolderUp size={23} /><div><b>Choose dataset folder</b><span>Select the parent folder, for example chest_xray. It must contain at least two image class folders such as NORMAL and PNEUMONIA.</span></div><button type="button" className="button secondary" disabled={busy}>Choose dataset</button>
      </div>
      {selectedDataset && <section className="dataset-summary">
        <div><FolderUp size={18} /><span><b>{selectedDataset.folderName}</b><br />Folder selected — ready for local validation and preparation.</span><button type="button" className="text-link" disabled={busy} onClick={event => { event.stopPropagation(); clearDataset(); }}>Clear dataset</button></div>
        <table><thead><tr><th>CLASS</th><th>IMAGES</th></tr></thead><tbody>{selectedDataset.classes.map(name => <tr key={name}><td>{name}</td><td>{selectedDataset.classDistribution[name].toLocaleString()}</td></tr>)}</tbody></table>
        <p>{selectedDataset.fileCount.toLocaleString()} images · {(selectedDataset.sizeBytes / 1024 / 1024).toFixed(1)} MB · Folder structure detected · Image integrity will be validated by the local ML service.</p>
        <div className="dataset-summary-actions"><button className="button primary" disabled={busy || Boolean(validation)} onClick={() => void uploadDataset()}>{busy ? 'Preparing…' : 'Prepare Dataset'} <ArrowRight size={16} /></button><small>Files are sent only to {localMlUrl}.</small></div>
      </section>}
      {uploadNotice && <div className="form-notice">{uploadNotice}</div>}
      {error && <div className="form-error">{error}</div>}
      <div className="training-actions"><label>Epochs<input type="number" min={1} max={100} value={epochs} onChange={event => setEpochs(Number(event.target.value))} /></label>{validation && <button className="button primary" disabled={busy} onClick={() => void train()}>{busy ? 'Training…' : 'Start Local Training'} <ArrowRight size={16} /></button>}</div>
      {validation && <div className="dataset-ready"><div><b>Validation passed: {validation.file_count.toLocaleString()} local images · {validation.classes.length} classes</b><span>{validation.classes.join(', ')} · {(validation.size_bytes / 1024 / 1024).toFixed(1)} MB · integrity checked locally</span></div></div>}
      {training.status !== 'idle' && <div className="class-note"><Activity size={16} /><span><b>Training status: {training.status}</b><br />{training.epoch ? `Epoch ${training.epoch} of ${training.total_epochs} · loss ${training.loss?.toFixed(4)} · accuracy ${((training.accuracy ?? 0) * 100).toFixed(1)}%` : training.checkpoint ?? training.message}</span></div>}
      {training.status === 'completed' && <div className="class-note"><ShieldCheck size={16} /><span><b>Local model update ready.</b><br />Parameters, tensor shapes, class definitions, and permitted metrics can be sent for the current round.<br /><button className="button primary" disabled={busy} onClick={() => void submit()}>{busy ? 'Submitting…' : 'Submit Model Update'}</button>{submitted && <small>{submitted}</small>}</span></div>}
    </section>
  </>;
}

function TrainingHistory() {
  const [items, setItems] = useState<Array<Training & { _id?: string; createdAt?: string }>>([]); const [error, setError] = useState('');
  useEffect(() => { fetch(centralApiUrl + '/api/training/runs', { headers: tokenHeaders() }).then(async response => { const data = await response.json(); if (!response.ok) throw new Error(data.message); setItems(data); }).catch(cause => setError(cause instanceof Error ? cause.message : 'Unable to load training history.')); }, []);
  return <><section className="page-heading"><div><div className="eyebrow">TRAINING HISTORY</div><h1>Local training runs</h1><p>Metadata recorded after hospital-local training; no images are retained here.</p></div></section>{error && <div className="form-error">{error}</div>}<section className="panel hospital-table"><table><thead><tr><th>STATUS</th><th>SAMPLES</th><th>LOSS</th><th>ACCURACY</th><th>RECORDED</th></tr></thead><tbody>{items.length ? items.map((item, index) => <tr key={item._id ?? index}><td>{item.status}</td><td>{item.samples?.toLocaleString() ?? 'Not available'}</td><td>{item.loss?.toFixed(4) ?? 'Not available'}</td><td>{item.accuracy === undefined ? 'Not available' : `${(item.accuracy * 100).toFixed(1)}%`}</td><td>{date(item.createdAt)}</td></tr>) : <tr><td colSpan={5}>No local training has been recorded.</td></tr>}</tbody></table></section></>;
}

export function Hospital({ onExit, path, onNavigate }: { onExit: () => void; path: string; onNavigate: (path: string) => void }) {
  const fragment = path.replace('/hospital/', ''); const view: View = fragment === 'dashboard' || !fragment ? 'overview' : nav.some(([id]) => id === fragment) ? fragment as View : 'overview';
  const content = view === 'overview' ? <Overview setView={next => onNavigate('/hospital/' + (next === 'overview' ? 'dashboard' : next))} /> : view === 'train' ? <LocalTrain /> : view === 'global-model' ? <LiveFederated /> : view === 'prediction' ? <Prediction /> : <TrainingHistory />;
  return <div className="app"><aside className="sidebar"><div className="brand"><div className="brand-mark"><ShieldCheck size={21} /></div><div><b>Arogya<span>Vaani</span></b><small>Privacy-preserved AI</small></div></div><nav>{nav.map(([id, label, Icon]) => <button key={id} className={view === id ? 'active' : ''} onClick={() => onNavigate('/hospital/' + (id === 'overview' ? 'dashboard' : id))}><Icon size={18} /><span>{label}</span></button>)}</nav><div className="sidebar-bottom"><button className="text-button" onClick={onExit}><LogOut size={15} /> Logout</button></div></aside><div className="main"><main>{content}</main><footer><span><ShieldCheck size={14} /> Images stay local by design</span></footer></div></div>;
}
