import { FormEvent, useEffect, useRef, useState } from 'react';
import { ArrowRight, Building2, Check, Eye, EyeOff, HeartPulse, LockKeyhole, ShieldCheck, UsersRound } from 'lucide-react';
import { centralApiUrl } from './config';

type Role = 'hospital' | 'admin';
declare global { interface Window { google?: { accounts: { id: { initialize: (options: { client_id: string; callback: (response: { credential?: string }) => void }) => void; renderButton: (element: HTMLElement, options: Record<string, unknown>) => void } } } } }

export function Landing({ onLogin }: { onLogin: () => void }) {
  return <div className="public-shell"><header className="public-nav"><a className="brand" href="#top" aria-label="ArogyaVaani home"><div className="brand-mark"><ShieldCheck size={20} /></div><b>ArogyaVaani</b></a><nav className="public-links"><a href="#top" className="active">Home</a><a href="#capabilities">Features</a><a href="#privacy">Security</a></nav><div className="nav-actions"><button className="button primary" onClick={onLogin}>Sign in</button></div></header><main className="landing" id="top"><section className="hero"><div className="hero-copy"><h1>Privacy-Preserved AI<br />for Better Healthcare</h1><p>A federated learning platform for hospitals to collaborate on model updates without sharing patient images or local datasets.</p><div className="hero-actions"><button className="button primary" onClick={onLogin}>Connect your hospital</button></div></div><div className="hero-visual" aria-label="Federated privacy boundary"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="hospital-orb orb-one"><Building2 size={18} /></div><div className="hospital-orb orb-two"><Building2 size={18} /></div><div className="hospital-orb orb-three"><Building2 size={18} /></div><div className="hospital-orb orb-four"><Building2 size={18} /></div><div className="shield-orb"><LockKeyhole size={45} /><span>Patient data<br />stays local</span></div></div></section><section className="capability-grid" id="capabilities"><div><LockKeyhole size={19} /><b>Privacy first</b><p>Images and datasets remain within the hospital environment.</p></div><div><UsersRound size={19} /><b>Collaborative learning</b><p>Hospitals contribute approved model updates to shared rounds.</p></div><div><ShieldCheck size={19} /><b>Role-protected access</b><p>Hospital and administrator workspaces are enforced by the API.</p></div><div><HeartPulse size={19} /><b>Clinical support</b><p>Local inference remains a clinician-reviewed decision-support tool.</p></div></section><section className="landing-security" id="privacy"><ShieldCheck size={21} /><div><b>Patient images are never sent to the central API.</b><p>Central storage is limited to federated model updates and operational metadata.</p></div></section></main></div>;
}

export function Auth({ startInSignup = false, onBack, onSuccess }: { startInSignup?: boolean; onBack: () => void; onSuccess: (token: string, role: Role) => void }) {
  const [mode, setMode] = useState<'login' | 'register' | 'google-onboarding'>(startInSignup ? 'register' : 'login');
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [confirmPassword, setConfirmPassword] = useState(''); const [hospitalName, setHospitalName] = useState(''); const [googleCredential, setGoogleCredential] = useState('');
  const [showPassword, setShowPassword] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false); const [googleReady, setGoogleReady] = useState<boolean | null>(null); const googleRef = useRef<HTMLDivElement>(null);
  const frontendGoogleId = import.meta.env.VITE_GOOGLE_CLIENT_ID as string | undefined;
  const [googleClientId, setGoogleClientId] = useState(() => frontendGoogleId && !/^replace-with-|^YOUR_CLIENT_ID|^your[-_]/i.test(frontendGoogleId) ? frontendGoogleId : undefined);
  const isRegister = mode === 'register'; const isOnboarding = mode === 'google-onboarding';
  useEffect(() => { fetch(centralApiUrl + '/api/auth/google/status').then(response => response.json()).then((data: { configured?: boolean; clientId?: string }) => { const clientId = data.clientId && !/^replace-with-|^YOUR_CLIENT_ID|^your[-_]/i.test(data.clientId) ? data.clientId : undefined; setGoogleClientId(current => current ?? clientId); setGoogleReady(Boolean(data.configured && (clientId || googleClientId))); }).catch(() => setGoogleReady(false)); }, []);
  const completeGoogle = async (credential: string, onboarding = false) => { setBusy(true); setError(''); setNotice(''); try { const response = await fetch(centralApiUrl + '/api/auth/google', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(onboarding ? { idToken: credential, hospitalName } : { idToken: credential }) }); const data = await response.json(); if (!response.ok) { if (response.status === 400 && String(data.message).toLowerCase().includes('hospital name')) { setGoogleCredential(credential); setMode('google-onboarding'); setNotice('Add your hospital name to finish verified Google registration.'); return; } throw new Error(data.message ?? 'Google sign-in could not be completed.'); } onSuccess(data.token, data.role); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Google sign-in could not be completed.'); } finally { setBusy(false); } };
  useEffect(() => { if (!googleClientId || !googleReady || !googleRef.current || isOnboarding) return; let cancelled = false; const render = () => { if (!cancelled && window.google && googleRef.current) { window.google.accounts.id.initialize({ client_id: googleClientId, callback: response => response.credential ? void completeGoogle(response.credential) : setError('Google sign-in did not complete. Please try again.') }); googleRef.current.replaceChildren(); window.google.accounts.id.renderButton(googleRef.current, { theme: 'outline', size: 'large', width: 330, text: 'continue_with', shape: 'rectangular' }); } }; const existing = document.querySelector<HTMLScriptElement>('script[data-google-identity]'); if (existing) { if (window.google) render(); else existing.addEventListener('load', render); return () => { cancelled = true; existing.removeEventListener('load', render); }; } const script = document.createElement('script'); script.src = 'https://accounts.google.com/gsi/client'; script.async = true; script.dataset.googleIdentity = 'true'; script.addEventListener('load', render); script.addEventListener('error', () => setError('Google sign-in is unavailable right now. Please use email and password.')); document.head.appendChild(script); return () => { cancelled = true; script.removeEventListener('load', render); }; }, [googleClientId, googleReady, isOnboarding]);
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); setNotice(''); if (isRegister && password !== confirmPassword) { setError('Passwords do not match.'); return; } if (isOnboarding) { if (!googleCredential) { setMode('login'); setError('Please start Google sign-in again.'); return; } await completeGoogle(googleCredential, true); return; } setBusy(true); try { const response = await fetch(centralApiUrl + (isRegister ? '/api/auth/register' : '/api/auth/login'), { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(isRegister ? { hospitalName, email, password } : { email, password }) }); const data = await response.json(); if (!response.ok) throw new Error(data.message ?? 'Authentication failed.'); if (isRegister) { setMode('login'); setNotice('Hospital account created. Sign in to continue.'); } else onSuccess(data.token, data.role); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Authentication failed.'); } finally { setBusy(false); } };
  const passwordControl = <label>Password<div className="password-control"><input required minLength={isRegister ? 12 : 1} type={showPassword ? 'text' : 'password'} value={password} onChange={event => setPassword(event.target.value)} /><button type="button" aria-label={showPassword ? 'Hide password' : 'Show password'} onClick={() => setShowPassword(value => !value)}>{showPassword ? <EyeOff size={17} /> : <Eye size={17} />}</button></div></label>;
  return <div className="auth-shell"><div className="auth-aside"><button className="brand-button" onClick={onBack}><div className="brand-mark"><HeartPulse size={20} /></div><b>Arogya<span>Vaani</span></b></button><div><div className="eyebrow">SECURE FEDERATED HEALTHCARE AI</div><h1>Train together.<br />Keep images local.</h1><p>Secure role-based access for hospital teams and network administrators.</p></div><div className="auth-aside-note"><Check size={15} /> Patient images never reach the central API</div></div><div className="auth-form-wrap"><button className="back-link" onClick={onBack}>‹ Back to ArogyaVaani</button><div className="auth-form"><div className="eyebrow">{isOnboarding ? 'GOOGLE REGISTRATION' : isRegister ? 'HOSPITAL REGISTRATION' : 'SECURE SIGN IN'}</div><h2>{isOnboarding ? 'Complete your hospital account' : isRegister ? 'Create Hospital Account' : 'Welcome back'}</h2><p>{isOnboarding ? 'Your Google identity is verified. Add the required hospital information.' : isRegister ? 'Join the privacy-preserved federated network.' : 'Sign in to your hospital or administrator workspace.'}</p><form onSubmit={submit}>{(isRegister || isOnboarding) && <label>Hospital Name<input required value={hospitalName} onChange={event => setHospitalName(event.target.value)} /></label>}{!isOnboarding && <><label>Email<input required type="email" autoComplete="email" value={email} onChange={event => setEmail(event.target.value)} /></label>{passwordControl}{isRegister && <label>Confirm Password<input required minLength={12} type={showPassword ? 'text' : 'password'} value={confirmPassword} onChange={event => setConfirmPassword(event.target.value)} /></label>}</>}{error && <div className="form-error" role="alert">{error}</div>}{notice && <div className="form-notice">{notice}</div>}<button className="button primary full" disabled={busy}>{busy ? 'Please wait…' : isOnboarding ? 'Complete Google sign-in' : isRegister ? 'Create Hospital Account' : 'Sign in'} <ArrowRight size={16} /></button></form>{!isOnboarding && <><div className="or"><span />OR<span /></div>{googleClientId && googleReady ? <div className="google-button" ref={googleRef} aria-label="Continue with Google" /> : <div className="google-unavailable">Google sign-in is not available for this deployment. You can continue with email and password.</div>}</>}{!isOnboarding && <div className="auth-switch">{isRegister ? <><span>Already have an account?</span> <button onClick={() => setMode('login')}>Sign in</button></> : <><span>New hospital?</span> <button onClick={() => setMode('register')}>Create an account</button></>}</div>}</div></div></div>;
}
